// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project. 
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc. 
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File". 
// You do not need to add suppressions to this file manually. 

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Cuemon", Scope = "namespace", Target = "Cuemon.Data")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Cuemon", Scope = "namespace", Target = "Cuemon.Data.Entity")]
[assembly: SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "Cuemon.Data.SqlClient")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Cuemon", Scope = "namespace", Target = "Cuemon.Data.SqlClient")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Cuemon")]
[assembly: SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "Cuemon.Data.Entity.IBusinessEntity.#GetIdentifier()")]
[assembly: SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "Cuemon.Data.Entity.BusinessEntity.#GetIdentifier()")]
[assembly: SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "Cuemon.Data.Entity.IIdentifier.#GetIdentifier()")]
[assembly: SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "Cuemon.Data.Entity.IIdentifiers.#GetIdentifiers()")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Cuemon", Scope = "namespace", Target = "Cuemon.Data.Mapping")]
[assembly: SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "Cuemon.Data.SqlClient.Entity")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Cuemon", Scope = "namespace", Target = "Cuemon.Data.SqlClient.Entity")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1813:AvoidUnsealedAttributes", Scope = "type", Target = "Cuemon.Data.Mapping.ColumnAttribute")]
[assembly: SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "Cuemon.Data.Entity.IBusinessEntityDataMapped.#GetDataMappedEntitiesColumns()")]
[assembly: SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "Cuemon.Data.Entity.IBusinessEntityCollection`1.#GetEntityType()")]
[assembly: SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "Cuemon.Data.DataManager.#GetDefaultDataConnectionElementFromConfigurationFile()")]
[assembly: SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "BusinessEntity", Scope = "member", Target = "Cuemon.Data.Entity.BusinessEntityDataAdapter.#Open(Cuemon.Data.IDataCommand,System.Data.IDataParameter[])")]
[assembly: SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "BusinessEntityDataAdapter", Scope = "member", Target = "Cuemon.Data.Entity.BusinessEntityDataAdapter.#Open(Cuemon.Data.IDataCommand,System.Data.IDataParameter[])")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2215:Dispose methods should call base class dispose", Scope = "member", Target = "Cuemon.Data.SqlClient.SqlDataConnection.#Dispose(System.Boolean)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2215:Dispose methods should call base class dispose", Scope = "member", Target = "Cuemon.Data.SqlClient.SqlDataManager.#Dispose(System.Boolean)")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Cuemon.Data.DataCommand.#ctor(System.String,System.Data.CommandType,System.TimeSpan)", Scope = "member", Target = "Cuemon.Data.SqlClient.SqlDataManager.#ExecuteIdentityDecimal(Cuemon.Data.IDataCommand,System.Data.IDataParameter[])")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Cuemon.Data.DataCommand.#ctor(System.String,System.Data.CommandType,System.TimeSpan)", Scope = "member", Target = "Cuemon.Data.SqlClient.SqlDataManager.#ExecuteIdentityInt32(Cuemon.Data.IDataCommand,System.Data.IDataParameter[])")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Cuemon.Data.DataCommand.#ctor(System.String,System.Data.CommandType,System.TimeSpan)", Scope = "member", Target = "Cuemon.Data.SqlClient.SqlDataManager.#ExecuteIdentityInt64(Cuemon.Data.IDataCommand,System.Data.IDataParameter[])")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "1", Scope = "member", Target = "Cuemon.Data.Entity.BusinessEntity.#SetCore(System.String,System.Object)")]
[assembly: SuppressMessage("Microsoft.Security", "CA2100:Review SQL queries for security vulnerabilities", Scope = "member", Target = "Cuemon.Data.SqlClient.SqlDataManager.#GetCommandCore(Cuemon.Data.IDataCommand,System.Data.IDataParameter[])")]
[assembly: SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "querytype", Scope = "member", Target = "Cuemon.Data.SqlClient.SqlQueryBuilder.#GetQuery(Cuemon.Data.QueryType,System.String)")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "Cuemon.Data.SqlClient.Entity.SqlBusinessEntityDataAdapter.#.ctor(Cuemon.Data.Entity.IBusinessEntityRepository)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1052:StaticHolderTypesShouldBeSealed", Scope = "type", Target = "Cuemon.Data.Entity.BusinessEntityEventArgs")]
[assembly: SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "DataAdapter", Scope = "member", Target = "Cuemon.Data.Entity.BusinessEntity.#Initialize()")]
[assembly: SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "InitializeDataAdapter", Scope = "member", Target = "Cuemon.Data.Entity.BusinessEntity.#Initialize()")]
[assembly: SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "DataAdapter", Scope = "member", Target = "Cuemon.Data.Entity.BusinessEntityCollection`1.#Initialize()")]
[assembly: SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "InitializeDataAdapter", Scope = "member", Target = "Cuemon.Data.Entity.BusinessEntityCollection`1.#Initialize()")]
[assembly: SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "Cuemon.Data.DataAdapterEventArgs.#Empty")]
[assembly: SuppressMessage("Microsoft.Design", "CA1063:ImplementIDisposableCorrectly", Scope = "member", Target = "Cuemon.Data.SqlClient.SqlDataManager.#Finalize()")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "Cuemon.Data.DataWatcher.#Parameters")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "Db", Scope = "member", Target = "Cuemon.Data.DataManager.#ParseDbType(System.Data.DbType)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "Db", Scope = "type", Target = "Cuemon.Data.DbColumn")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "Db", Scope = "member", Target = "Cuemon.Data.DbColumn.#.ctor(System.Data.DbType,System.Object)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "Db", Scope = "member", Target = "Cuemon.Data.DbColumn.#ColumnDbType")]
[assembly: SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Cuemon.Data.DataManager.#GetReaderColumns(System.Data.IDataReader)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "Cuemon.Data.DataManager.#ExecuteCommandCore(Cuemon.Data.IDataCommand,System.Data.IDataParameter[])")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "Cuemon.Data.DataManager.#ExecuteScalarImpl(System.Data.IDbCommand)")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "Cuemon.Data.SqlClient.SqlDataManager.#GetCommandCore(Cuemon.Data.IDataCommand,System.Data.IDataParameter[])")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "Cuemon.Data.DataManager.#ExecuteReaderImpl(System.Data.IDbCommand)")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "Cuemon.Data.DataManager.#ExecuteImpl(System.Data.IDbCommand)")]
[assembly: SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Scope = "member", Target = "Cuemon.Data.SqlClient.SqlDataManager.#IsTransientFault(System.Exception)")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "Cuemon.Data.DataManager.#ExecuteReaderCore(System.Data.IDbCommand)")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "Cuemon.Data.DataManager.#ExecuteCore(System.Data.IDbCommand)")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "Cuemon.Data.DataManager.#ExecuteScalarCore(System.Data.IDbCommand)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1053:StaticHolderTypesShouldNotHaveConstructors", Scope = "type", Target = "Cuemon.Data.DataAdapterEventArgs")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "Cuemon.Data.InOperator`1.#Parameters")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Cuemon", Scope = "namespace", Target = "Cuemon.Data.XmlClient")]
[assembly: SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "Cuemon.Data.XmlClient")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Cuemon.Data.StringDataReader.#System.Data.IDataReader.RecordsAffected")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Cuemon.Data.StringDataReader.#System.Data.IDataReader.Close()")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Cuemon.Data.StringDataReader.#System.Data.IDataReader.NextResult()")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Cuemon.Data.StringDataReader.#System.Data.IDataReader.GetSchemaTable()")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Cuemon.Data.StringDataReader.#System.Data.IDataRecord.GetChars(System.Int32,System.Int64,System.Char[],System.Int32,System.Int32)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Cuemon.Data.StringDataReader.#System.Data.IDataRecord.GetData(System.Int32)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Cuemon.Data.StringDataReader.#System.Data.IDataRecord.GetDataTypeName(System.Int32)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Cuemon.Data.StringDataReader.#System.Data.IDataRecord.GetBytes(System.Int32,System.Int64,System.Byte[],System.Int32,System.Int32)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2215:Dispose methods should call base class dispose", Scope = "member", Target = "Cuemon.Data.XmlClient.XmlDataReader.#Dispose(System.Boolean)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Cuemon.Data.StringDataReader.#GetValues(System.Object[])")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2215:Dispose methods should call base class dispose", Scope = "member", Target = "Cuemon.Data.CsvClient.CsvDataReader.#Dispose(System.Boolean)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "Cuemon.Data.CsvClient.CsvDataReader.#Header")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "1", Scope = "member", Target = "Cuemon.Data.CsvClient.CsvDataReader.#.ctor(System.IO.StreamReader,System.String,System.String,Cuemon.Doer`2<System.String,System.Object>)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "Cuemon.Data.CsvClient")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Cuemon", Scope = "namespace", Target = "Cuemon.Data.CsvClient")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Cuemon.Data.SqlClient.SqlDataManager.#ExecuteBulk(Cuemon.Data.StringDataReader,System.String)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Cuemon.Data.SqlClient.SqlDataManager.#ExecuteBulk(Cuemon.Data.StringDataReader,System.String,System.Data.SqlClient.SqlBulkCopyOptions)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Cuemon.Data.SqlClient.SqlDataManager.#ExecuteBulk(Cuemon.Data.StringDataReader,System.String,System.Data.SqlClient.SqlBulkCopyOptions,System.TimeSpan)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Cuemon.Data.SqlClient.SqlDataManager.#Parse(Cuemon.Mapping)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Cuemon.Data.SqlClient.SqlDataManager.#Parse(System.Data.SqlClient.SqlBulkCopyColumnMapping)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Cuemon.Data.MappedDataReader.#GetValues(System.Object[])")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Cuemon.Data.BulkCopyDataReader.#GetValues(System.Object[])")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Cuemon.Data.DataTransferRowCollection.#IsReadOnly")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Cuemon.Data.DataTransferColumnCollection.#IsReadOnly")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Cuemon.Data.DataTransfer.#GetPagedRows(System.Data.IDataReader,System.Int32,System.Int32)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Cuemon.Data.DataTransfer.#GetRows(System.Data.IDataReader)")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Cuemon.Validator.ThrowIfTrue(System.Boolean,System.String,System.String)", Scope = "member", Target = "Cuemon.Data.DataTransfer.#GetRows(System.Data.IDataReader)")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Cuemon.Validator.ThrowIfTrue(System.Boolean,System.String,System.String)", Scope = "member", Target = "Cuemon.Data.DataTransfer.#GetPagedRows(System.Data.IDataReader,System.Int32,System.Int32)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Cuemon.Data.DataTransfer.#GetColumns(System.Data.IDataReader)")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Cuemon.Validator.ThrowIfTrue(System.Boolean,System.String,System.String)", Scope = "member", Target = "Cuemon.Data.DataTransfer.#GetColumns(System.Data.IDataReader)")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Cuemon.Validator.ThrowIfTrue(System.Boolean,System.String,System.String)", Scope = "member", Target = "Cuemon.Data.DataTransferRowCollection.#.ctor(System.Data.IDataReader)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Cuemon.Data.DataTransfer.#GetPagedRows(Cuemon.Doer`2<Cuemon.Collections.Generic.PagedSettings,System.Collections.Generic.IEnumerable`1<Cuemon.Data.DataTransferRow>>,Cuemon.Doer`2<Cuemon.Collections.Generic.PagedSettings,System.Int32>,Cuemon.Collections.Generic.PagedSettings)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Cuemon.Data.DataTransfer.#GetPagedRows(Cuemon.Collections.Generic.PagedSettings,Cuemon.Doer`2<Cuemon.Collections.Generic.PagedSettings,System.Collections.Generic.IEnumerable`1<Cuemon.Data.DataTransferRow>>,Cuemon.Doer`2<Cuemon.Collections.Generic.PagedSettings,System.Int32>)")]
