// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File".
// You do not need to add suppressions to this file manually.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Cuemon", Scope = "namespace", Target = "Cuemon.ServiceModel.Diagnostics")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Cuemon")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Cuemon", Scope = "namespace", Target = "Cuemon.ServiceModel")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Cuemon.ServiceModel.EndPoint.#Cache")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", MessageId = "Cuemon.ConvertUtility.ChangeType(System.Object,System.Type)", Scope = "member", Target = "Cuemon.ServiceModel.EndPoint.#GetMethodToInvoke(System.Uri,System.Collections.Generic.IEnumerable`1<System.Reflection.MethodInfo>,System.Object[]&)")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", MessageId = "Cuemon.ConvertUtility.ChangeType(System.Object,System.Type)", Scope = "member", Target = "Cuemon.ServiceModel.Endpoint.#GetMethodToInvoke(System.Uri,System.Collections.Generic.IEnumerable`1<System.Reflection.MethodInfo>,System.Object[]&)")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", MessageId = "Cuemon.ConvertUtility.ChangeType(System.Object,System.Type)", Scope = "member", Target = "Cuemon.ServiceModel.Endpoint.#GetMethodToInvoke(System.Uri,System.Collections.Generic.IEnumerable`1<System.Reflection.MethodInfo>,Cuemon.Net.Http.HttpMethods,System.Object[]&)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Cuemon.ServiceModel.Endpoint.#Cache")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", MessageId = "System.Convert.ToString(System.Object)", Scope = "member", Target = "Cuemon.ServiceModel.EndpointModule.#HandleExceptionInterception(System.Web.HttpApplication,System.Boolean)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "Cuemon.ServiceModel.HttpRouteAttribute.#RouteArgumentsAsHexString")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "Cuemon.ServiceModel.HttpRouteAttribute.#CompoundPathSegments")]
[assembly: SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "Deserilization", Scope = "member", Target = "Cuemon.ServiceModel.Endpoint.#ParseInputStream(System.Reflection.MethodInfo,System.IO.Stream,System.String,System.Uri,Cuemon.Net.Http.HttpMethods,System.Text.Encoding)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "Cuemon", Scope = "member", Target = "Cuemon.ServiceModel.Endpoint.#ParseInputStream(System.Reflection.MethodInfo,System.IO.Stream,System.String,System.Uri,Cuemon.Net.Http.HttpMethods,System.Text.Encoding)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "ServiceModel", Scope = "member", Target = "Cuemon.ServiceModel.Endpoint.#ParseInputStream(System.Reflection.MethodInfo,System.IO.Stream,System.String,System.Uri,Cuemon.Net.Http.HttpMethods,System.Text.Encoding)")]
[assembly: SuppressMessage("Microsoft.Portability", "CA1903:UseOnlyApiFromTargetedFramework", MessageId = "System.Web.Compilation.BuildManager.#GetReferencedAssemblies()", Scope = "member", Target = "Cuemon.ServiceModel.EndpointModule.#OnApplicationStart(System.Web.HttpApplication)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "Cuemon.ServiceModel.Endpoint.#ExcecuteOperationCore(System.Reflection.MethodBase,Cuemon.ActionFactory)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "Cuemon.ServiceModel.Endpoint.#ExcecuteOperationResponseCore`1(System.Reflection.MethodBase,Cuemon.FuncFactory`1<!!0>,Cuemon.ActionFactory)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "Cuemon.ServiceModel.Endpoint.#ExcecuteOperationCore(System.Reflection.MethodBase,Cuemon.OperationFactory)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "Cuemon.ServiceModel.Endpoint.#ExcecuteFunctionCore`1(System.Reflection.MethodBase,Cuemon.OperationResultFactory`1<!!0>,Cuemon.Caching.CacheValidator,System.Web.HttpCacheability)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "Cuemon.ServiceModel.Endpoint.#ExcecuteActionCore(System.Reflection.MethodBase,Cuemon.ActFactory)")]
[assembly: SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Scope = "type", Target = "Cuemon.ServiceModel.Endpoint")]
[assembly: SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "Cuemon.ServiceModel.Endpoint.#ExcecuteFunctionCore`1(System.Reflection.MethodBase,Cuemon.DoerFactory`1<!!0>,Cuemon.Caching.CacheValidator,System.Web.HttpCacheability)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1021:AvoidOutParameters", MessageId = "3#", Scope = "member", Target = "Cuemon.ServiceModel.Endpoint.#ClientSideCachingHandler(Cuemon.Caching.CacheValidator,System.DateTime,System.Web.HttpCacheability,System.Boolean&)")]
[assembly: SuppressMessage("Microsoft.Portability", "CA1903:UseOnlyApiFromTargetedFramework", MessageId = "System.Web.HttpResponse.#get_Headers()", Scope = "member", Target = "Cuemon.ServiceModel.Endpoint.#ClientSideCachingHandler(Cuemon.Caching.CacheValidator,System.DateTime,System.Web.HttpCacheability,System.Boolean&)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "Cuemon.ServiceModel.Endpoint.#ExcecuteFunctionCore`1(System.Reflection.MethodBase,Cuemon.DoerFactory`1<!!0>,Cuemon.Caching.CacheValidator,System.Nullable`1<System.Web.HttpCacheability>)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "Cuemon.ServiceModel.Endpoint.#ExecuteActionCore(System.Reflection.MethodBase,Cuemon.ActFactory)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "Cuemon.ServiceModel.Endpoint.#ExecuteFunctionCore`1(System.Reflection.MethodBase,Cuemon.DoerFactory`1<!!0>,Cuemon.Caching.CacheValidator,System.Nullable`1<System.Web.HttpCacheability>)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Deserializer", Scope = "member", Target = "Cuemon.ServiceModel.HttpMessageBody`1.#Deserializer")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors", Scope = "member", Target = "Cuemon.ServiceModel.HttpMessageBody`1.#.ctor(System.Net.Mime.ContentType,System.Text.Encoding,Cuemon.Doer`3<System.IO.Stream,System.Text.Encoding,!0>)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "deserializer", Scope = "member", Target = "Cuemon.ServiceModel.HttpMessageBody`1.#.ctor(System.Net.Mime.ContentType,System.Text.Encoding,Cuemon.Doer`3<System.IO.Stream,System.Text.Encoding,!0>)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors", Scope = "member", Target = "Cuemon.ServiceModel.HttpMessageBody`1.#.ctor(System.Net.Mime.ContentType,System.Text.Encoding)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "deserializer", Scope = "member", Target = "Cuemon.ServiceModel.XmlMessageBody`1.#.ctor(System.Net.Mime.ContentType,System.Text.Encoding,Cuemon.Doer`3<System.IO.Stream,System.Text.Encoding,!0>)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "deserializer", Scope = "member", Target = "Cuemon.ServiceModel.HttpMessageBody`1.#.ctor(System.Net.Mime.ContentType,System.Text.Encoding,Cuemon.Doer`4<System.IO.Stream,System.Net.Mime.ContentType,System.Text.Encoding,!0>)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors", Scope = "member", Target = "Cuemon.ServiceModel.HttpMessageBody`1.#.ctor(System.Net.Mime.ContentType,System.Text.Encoding,Cuemon.Doer`4<System.IO.Stream,System.Net.Mime.ContentType,System.Text.Encoding,!0>)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "Cuemon.ServiceModel.HttpMultipartContent.#GetPartAsFile()")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "Cuemon.ServiceModel.HttpMultipartContent.#Data")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", MessageId = "Cuemon.ConvertUtility.ChangeType(System.Object,System.Type)", Scope = "member", Target = "Cuemon.ServiceModel.Endpoint.#ParseMultipart(System.Text.Encoding,System.Collections.Generic.IEnumerable`1<Cuemon.ServiceModel.HttpMultipartContent>,System.Collections.Generic.IEnumerable`1<System.Reflection.PropertyInfo>,System.Object&)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "deserializer", Scope = "member", Target = "Cuemon.ServiceModel.XmlMessageBody`1.#.ctor(System.Net.Mime.ContentType,System.Text.Encoding,Cuemon.Doer`4<System.IO.Stream,System.Net.Mime.ContentType,System.Text.Encoding,!0>)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2200:RethrowToPreserveStackDetails", Scope = "member", Target = "Cuemon.ServiceModel.Endpoint.#ProcessRequest(System.Web.HttpContext)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2234:PassSystemUriObjectsInsteadOfStrings", Scope = "member", Target = "Cuemon.ServiceModel.Endpoint.#ProcessRequest(System.Web.HttpContext)")]
